name: New Jersey District Key Club Website
author: New Jersey District Key Club

markdown: redcarpet
markdown_ext: md
redcarpet:
    extensions: ["disable_indented_code_blocks", "space_after_headers", "with_toc_data"]

permalink: /news/blog/:categories/:title
highlighter: null

paginate: 4
paginate_path: /page/:num
